### ISSUE TITLE
Wrong links for GB Cartridge

### ISSUE THREAD

**Issue by hmax42** [EstebanFuentealba/MALVEKE-Flipper-Zero#12]
The 4 links to flipc.org for the "gb cartridge" leads all to "gb link-camera"
The erroneous links are here, all4 variants leads to "gb link camera"
https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/tree/main/flipper_companion_apps/applications/external/malveke_gb_cartridge

and the real fap has some kind of build error
https://flipc.org/EstebanFuentealba/MALVEKE-Flipper-Zero?branch=main&root=flipper_companion_apps%2Fapplications%2Fexternal%2Fmalveke_gb_cartridge

**Comment by EstebanFuentealba** [comment]
Thank you for reporting the issue! I've just fixed it.

Best regards!
