### ISSUE TITLE
add a single file .Bin for updating MALVEKE board with esp flasher 

### ISSUE THREAD

**Issue by mindstormpro3** [EstebanFuentealba/MALVEKE-Flipper-Zero#13]
the app "esp flasher" on flipper zero is compatable with the esp32-S2 so why not use it to update it?

**Comment by EstebanFuentealba** [comment]
Currently, **MALVEKE** can be updated through [this link](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/blob/main/webinstaller/README.md). This website is designed to upload and flash the [files located here](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/tree/main/webinstaller/public/firmware) onto the ESP32-S2. Perhaps these same files will be useful for what you intend to do. 
It's important to note that **MALVEKE** writes to the **SPIFFS** partition with necessary files for reading Game Boy Advance games.


https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/blob/dcfc931dc79f0ef5847a2a1657fd9aca58a7e6c9/webinstaller/src/App.vue#L10-L22
