### ISSUE TITLE
Wifi devboard capabilities

### ISSUE THREAD

**Issue by FerdinandoPH** [EstebanFuentealba/MALVEKE-Flipper-Zero#3]
I've read that, apart of all the awesome gb capabilities, malveke also has an ESP32-S2 with Marauder. Does this mean that I can also use Malveke as a normal Flipper Zero Wifi devboard? (like https://shop.flipperzero.one/products/wifi-devboard). I'm asking this because I was thinking of buying a wifi devboard, but if Malveke does the same thing and more, I'll wait until malveke is back on sale

**Comment by EstebanFuentealba** [comment]
The official **WiFi Dev Board** doesn't offer the same functionalities, as it comes with the [**Black Magic Probe (firmware)**](https://github.com/flipperdevices/blackmagic-esp32-s2), mainly designed for WiFi debugging purposes. MALVEKE, however, features the ESP32 Marauder (firmware), enabling the use of the official app [**[ESP32] WiFi Marauder**](https://github.com/0xchocolate/flipperzero-wifi-marauder/) and its functions seamlessly.


https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/442927/55b6a993-4aaa-4c58-9388-41a32f9c00d8

_Apologies for the video edits; some sections are sped up 2x because GitHub only allows uploads smaller than 10MB._

**Comment by FerdinandoPH** [comment]
> The official **WiFi Dev Board** doesn't offer the same functionalities, as it comes with the [**Black Magic Probe (firmware)**](https://github.com/flipperdevices/blackmagic-esp32-s2), mainly designed for WiFi debugging purposes. MALVEKE, however, features the ESP32 Marauder (firmware), enabling the use of the official app [**[ESP32] WiFi Marauder**](https://github.com/0xchocolate/flipperzero-wifi-marauder/) and its functions seamlessly.
> 
> 
> https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/442927/55b6a993-4aaa-4c58-9388-41a32f9c00d8
> 
> _Apologies for the video edits; some sections are sped up 2x because GitHub only allows uploads smaller than 10MB._
> 


As far as I know, the official wifi devboard is just an ESP32 that connects to the flipper zero. You can flash different programs to the devboard's ESP32 for using different flipper zero programs (one of them being Marauder).

What I meant to ask is: can the Malveke's ESP32 also be reflashed to use other flipper zero apps that use the wifi devboard, other than Marauder?

**Comment by EstebanFuentealba** [comment]
Absolutely, you can flash any firmware for ESP32-S2 using the Arduino IDE.

To upload any firmware of the board, follow these steps:

1. First, disconnect all modules (GPS, CC1101, and NRF modules), and remove the cartridge. Leave the board with nothing connected.

2. With MALVEKE connected to the flipper, connect the Flipper Zero to your computer via USB.

3. On the Flipper Zero, navigate to the GPIO menu and select "USB-UART Bridge."
<img width="1090" alt="280918923-ae965dc3-fcab-49e8-9844-2489ae859534" src="https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/442927/6eb67925-aa86-4746-90c9-50588d3b3142">

4. In MALVEKE Board press the "**BOOT**" button and while keeping it pressed, press the "**RESET**" button and Release both.

5. Open Arduino IDE and configure with this options:

![Captura_de_pantalla_2023-11-17_a_las_18 17 06](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/442927/13bc4ae4-da58-4e5f-852d-6eb8f60f1e85)

6. In Arduino IDE, press '**Upload**' and wait for all the data to be transferred.

<img width="675" alt="Captura de pantalla 2023-11-18 a la(s) 10 34 04" src="https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/442927/64b857dc-7260-4adf-8b36-6ff65cca70c3">

7. Reset MALVEKE board



**Considerations to keep in mind**:
- Some firmware may require additional connections, such as the ones needed for the [Wifi Dev Board](https://docs.flipper.net/development/hardware/wifi-developer-board#W95Xj) (SWCLK, SWDIO)
- MALVEKE lacks a MicroSD slot, so it utilizes Serial1 (U1TXD, U1RXD) to transmit files.

**Comment by FerdinandoPH** [comment]
Great!! I can't wait to get one once they're restocked!!

**Comment by FerdinandoPH** [comment]
Any plans on restocking, by the way?

**Comment by EstebanFuentealba** [comment]
This week
