### ISSUE TITLE
Gameboy Classic transfer buggy

### ISSUE THREAD

**Issue by explit28** [EstebanFuentealba/MALVEKE-Flipper-Zero#6]
Hello, and thanks for the great product!
While the transfer of pics from my Gameboy Light / JP Camera works fine, transfer from the classic Gameboy with the same JP Camera always fail.

I have no other Gameboys to test. Will investigate in the future.

**Comment by EstebanFuentealba** [comment]
Hi, I also don't have a DMG to test, but I'll get one to see what might be causing the issue. I have these available:

![IMG_20231212_123936](https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/assets/442927/7c5551aa-8a01-4e53-9d30-29667eea5aae)

**Comment by explit28** [comment]
I can help with betatesting, Thanks again for your work

**Comment by EstebanFuentealba** [comment]
I will temporarily close this issue while I thoroughly review the Camera - Cable Link #8 application. I've added another application, **[GAME BOY Photo](/EstebanFuentealba/MALVEKE-Flipper-Zero/blob/main/flipper_companion_apps/applications/external/malveke_gb_photo/README.md)**, which fulfills the need to save images from the GAME BOY Camera. This application will also have a web server to view all images and create backups.
