### ISSUE TITLE
Camera app calls the backlight notification on every frame

### ISSUE THREAD

**Issue by eried** [EstebanFuentealba/MALVEKE-Flipper-Zero#7]
Not very noticeable on OG flipper (might also affect performance with orange background?), but with rgb hack is evident
https://photos.app.goo.gl/yvLVVXdJaxbspCkr5

**Comment by EstebanFuentealba** [comment]
I've eliminated a notification that was triggering with each frame and causing the screen to power on. Can you test it out ?

https://github.com/EstebanFuentealba/MALVEKE-Flipper-Zero/commit/ed96373194cef5008a93a24ddfe2d5f9445adfc5#diff-bf6ad2454152cf51c368448a694ffb32f2ca1a20c1603e1e09ef04b06a3d8e62L228
